# Generated by Django 4.2.3 on 2025-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
